### ISSUE TITLE
Issue with *some* missions that expand - not ALL

### ISSUE THREAD

**Issue by MC-bot-test** [jackbayliss/Mission-Chief-Bot#33] opened 2020-06-19 22:05 UTC
I was running 0.0.9.6 on AU server with NO problems.

I updated to 0.0.9.7 and have had a couple of crashes. Each time it has been when a mission has expanded. If I get the mission it expands up to originally - no problems, it's only when the mission expands. It does not happen on all missions, and I thought it was isolated to just one, but I just got a second one.

I copied all my mission files over as I have amended a few as per your advice on my Issue #27 post.

I have attached the 'edited; debug reports because I have no idea what they refer to

[debug edited mission 143.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4806828/debug.edited.mission.143.txt)
[debug edited mission 29.txt](https://github.com/jackbayliss/Mission-Chief-Bot/files/4806830/debug.edited.mission.29.txt)

*** Side note 1 - the "EXPERIMENTAL" in the latest config file works perfectly on the AU server. Thanks.

*** Side note 2 - I was having issues with crashing on my US server test with 0.0.9.6, but 0.0.9.7 has fixed that. Thanks.

**Comment by jackbayliss** [comment] 2020-06-20 13:17
Thanks for the report, I’ll take a look into this and have it patched into the next update. 0.0.9.7 is meant to provide less crashes for the servers experiencing it every time. The debug logs make it easy to see where the issue is so I’ll sort this out soon.

**Comment by jackbayliss** [comment] 2020-06-20 18:31
After looking into it, it doesn't seem to be crashing due to actually expanding- but because of the experimental ambulance ability- this has been patched in my version so will release. Potentially disable it, and the crashing should stop :)

**Comment by jackbayliss** [comment] 2020-06-20 18:31
@MC-bot-test  After looking into it, it doesn't seem to be crashing due to actually expanding- but because of the experimental ambulance ability- this has been patched in my version so will release. Potentially disable it, and the crashing should stop :)

**Comment by jackbayliss** [comment] 2020-06-21 09:41
Closing, fixed in new version. Will be released soon.

**Closed by jackbayliss** 2020-06-21 09:41 UTC
