### ISSUE TITLE
emergency medical vehicle & rescue transport helicopter are not sent

### ISSUE THREAD

**Issue by Kulifloerkus** [jackbayliss/Mission-Chief-Bot#2] opened 2020-05-07 10:06 UTC
if a emergency medical vehicle or a rescue transport helicopter is needed, the bot send another  ambulance

**Comment by jackbayliss** [comment] 2020-05-07 10:08
@Kulifloerkus What region? DE, UK etc? Also, if possible could you give me the mission name?

**Comment by Kulifloerkus** [comment] 2020-05-07 10:12
DE, for example "Stromschlag", "Schlaganfall"
Command cars are not sent too, for example to "Massenpanik in Diskothek"

**Comment by vossejongk** [comment] 2020-05-07 10:16
Can confirm, happens in NL version as well

**Comment by jackbayliss** [comment] 2020-05-07 10:45
@vossejongk  @Kulifloerkus 
The answer is in your missions folder, for example Stromschlag is : 
https://www.leitstellenspiel.de/einsaetze/281

This converts into 281.json inside /de/missions : 
`{"missionId": "281", "missionName": "Stromschlag", "requirements": [{"requirement": "maximale patientenanzahl", "qty": "1"}]}`

The only way to fix this is to edit that file and we can then push it to the rest of the community  (so that it wont happen again) as the generator only goes off of the url https://www.leitstellenspiel.de/einsaetze/281

If you're confused how it works: 
See - https://www.leitstellenspiel.de/einsaetze/0
The bot will read that we need Löschfahrzeuge x 1, the links.json then tells us what kind of vehicle a Löschfahrzeuge is. If it's missing vehicles you will need to add the category as such. 

It however, doesn't understand the percentages (So if its just showing a percentage without a unit qty it won't know)

**Comment by Stiker839** [comment] 2020-05-07 11:16
I can confirm this is an issue accross all versions of the game, the only way to fix it is a manual edit untill the program can understand the percentage chance that Jack mentioned above.

**Comment by Kulifloerkus** [comment] 2020-05-07 14:30
Prisoners are not transported

**Comment by jackbayliss** [comment] 2020-05-07 15:18
@Kulifloerkus  If you have issues with prisoners, please create a separate issue. I will need to test it on an account with prisoners.

Closing this issue, as it's known due to the percentages. A fix would be that regardless of the percentage make the unit quantity 1. But, for now I would suggest manually fixing any broken missions and creating a pull request. This will allow for fixes for the communities of your region.

**Closed by jackbayliss** 2020-05-07 15:18 UTC
Labels: question
