### ISSUE TITLE
[ISSUE] Bot Failing to Hire Staff now

### ISSUE THREAD

**Issue by Fogest** [jackbayliss/Mission-Chief-Bot#63] opened 2020-10-12 00:27 UTC
**Describe the bug**
Originally having the hire staff flag set to `true` had no issues and staff were being hired for 3 days in each building. Now however that has stopped working for me causing the script to crash when I start it up. The fix is to just disable the hiring of staff automatically, but obviously that is not ideal. 

**Expected behaviour**
Staff are hired for 3 days at all buildings. Instead the bot crashes and does no hiring.

**Screenshots**
![image](https://user-images.githubusercontent.com/1163628/95694401-dd29c400-0bff-11eb-8444-25ac3d8a16e0.png)

Then after that the bots seems to restart and then throws a JSONDecodeError when it attempts to hire staff:

![image](https://user-images.githubusercontent.com/1163628/95694420-ffbbdd00-0bff-11eb-90d1-0d6e2de80f2e.png)

** Bot version and region **
Latest 0.1.4 on US region

**Additional context**
I am getting a JSON decode error. The initially error is spitting out content from the obfuscated code and is not very helpful. But then it gets a JSON decode error after that. Let me know if you want that full error output if you can't reproduce.

**Comment by jackbayliss** [comment] 2020-10-12 00:34
Correct, the issue is because the bot is appending a new date at the end of the laststarted.json in the json folder. To fix it, simply delete the file- or set hire_staff to false. Will be fixed with the next update 👍🏻

**Closed by jackbayliss** 2020-10-12 00:34 UTC
Labels: inqueue

**Comment by Fogest** [comment] 2020-10-12 00:37
Appreciate the quick response, thanks!
